services:
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=pass1
      - POSTGRES_DB=db1
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432

  pgcli:
    image: amixlabs/pgcli:3
    command: postgresql://user1:pass1@pg/db1
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - pgcli-home:/root
    links:
      - pg

volumes:
  pg-data:
  pgcli-home:
